// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcmb-4amtelPyvh5-_9yXcel7kJjkn1jE',
    appId: '1:187467978087:web:ab3d04563d325a03d88bc2',
    messagingSenderId: '187467978087',
    projectId: 'gdg-push',
    authDomain: 'gdg-push.firebaseapp.com',
    storageBucket: 'gdg-push.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQl7rZzBJjJ8reJzFRecCJH0lkcmGz5ro',
    appId: '1:187467978087:android:7ccda515cebe8cfdd88bc2',
    messagingSenderId: '187467978087',
    projectId: 'gdg-push',
    storageBucket: 'gdg-push.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjJCzhRC62yvocO6q1lqCs5KnBs5rF4k',
    appId: '1:187467978087:ios:019f50ef9921e6c0d88bc2',
    messagingSenderId: '187467978087',
    projectId: 'gdg-push',
    storageBucket: 'gdg-push.appspot.com',
    iosBundleId: 'com.example.gdgica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjJCzhRC62yvocO6q1lqCs5KnBs5rF4k',
    appId: '1:187467978087:ios:f6b31f339ddc4553d88bc2',
    messagingSenderId: '187467978087',
    projectId: 'gdg-push',
    storageBucket: 'gdg-push.appspot.com',
    iosBundleId: 'com.example.gdgica.RunnerTests',
  );
}
